### ISSUE TITLE
How often to make a new release? How to handle versioning?

### ISSUE THREAD

**Issue by YHordijk** [TheoChem-VU/TCutility#21]
I am wondering how often we should make a new release. As I see it now, every merge is a potential fully functional release. I propose we create a new release every merge-request. 
About version numbering. We should probably follow the x.y.z convention, where x is the major version (currently 0), y is the minor version and z is the micro version. I propose:
 - major version should be incremented when a module is feature-complete,
 - increment the minor version number after every succesful merge,
 - bug fixes should increment the micro version and should also be published as a release.
 
Please let me know your thoughts!

**Comment by SiebeLeDe** [comment]
I see and I agree with you to have a decisive, shared way to keep track of versions. Splitting the version in three degrees is a good idea! 

Just some checks: 
- The micro version should always be "0" when a new release is made right? Because then it should not contain any bugfixes since these were bugs from previous versions.
- You say that each merge is a potential fully functional release. I agree with that since we do not really have runtime complexities in different environment (such as plams with running jobs etc). I am only not use whether every small bug fix should result in a new release like you say with  

> bug fixes should increment the micro version and should also be published as a release

**Comment by SiebeLeDe** [comment]
Can be close this issue? It seems that we use this kind of versioning now (also known as semantic versioning)
